version: '3'
services:
  container-1:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    volumes:
      # mount the root folder that contains .git
      - .:/workspaces:cached
    command: sleep infinity
    links:
      - container-2
    # ...

  container-2:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      # mount the root folder that contains .git
      - .:/workspaces:cached
    command: sleep infinity
    # ...
